languageCode: "en-us"
title: "aldente"
baseURL: "http://cse125.ucsd.edu/2017/cse125g1/aldente-site/public/"
theme: "hyde"
metaDataFormat: "yaml"

params:
  themeColor: "theme-base-0d"
  description: "CSE 125"
